@startuml
left to right direction
package User {
  actor Player
  actor "spectator" as spectator
}
package ChessGame {
  usecase "Play" as Play
  usecase "Reset" as Reset
  usecase "Pause" as Pause
  usecase "Move" as Move
  usecase "Quit" as Quit
  usecase "View" as View
}
Player --> Play
Player --> Reset
Player --> Pause
Player --> Move
Player --> Quit
Player --> View
spectator --> View


@enduml